package trpcgo_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/befabri/trpcgo"
)

func TestGenerateTS(t *testing.T) {
	type Base struct {
		ID        string     `json:"id"`
		CreatedAt time.Time  `json:"createdAt"`
		DeletedAt *time.Time `json:"deletedAt,omitempty"`
	}
	type UserInput struct {
		Name  string   `json:"name"`
		Email string   `json:"email"`
		Tags  []string `json:"tags,omitempty"`
	}
	type UserOutput struct {
		Base
		Name  string            `json:"name"`
		Email string            `json:"email"`
		Meta  map[string]string `json:"meta,omitempty"`
	}

	router := trpcgo.NewRouter()
	trpcgo.Query(router, "user.getById", func(ctx context.Context, input struct {
		ID string `json:"id"`
	}) (UserOutput, error) {
		return UserOutput{}, nil
	})
	trpcgo.VoidQuery(router, "user.list", func(ctx context.Context) ([]UserOutput, error) {
		return nil, nil
	})
	trpcgo.Mutation(router, "user.create", func(ctx context.Context, input UserInput) (UserOutput, error) {
		return UserOutput{}, nil
	})
	trpcgo.VoidSubscribe(router, "user.events", func(ctx context.Context) (<-chan UserOutput, error) {
		return nil, nil
	})

	outputPath := filepath.Join(t.TempDir(), "trpc.ts")
	if err := router.GenerateTS(outputPath); err != nil {
		t.Fatalf("GenerateTS failed: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}
	output := string(data)

	t.Run("header", func(t *testing.T) {
		if !strings.HasPrefix(output, "// Code generated by trpcgo. DO NOT EDIT.") {
			t.Errorf("missing or wrong header")
		}
	})

	t.Run("UserOutput interface fields", func(t *testing.T) {
		// Must contain the interface with correct field types.
		mustContain := []string{
			"export interface UserOutput {",
			"name: string;",
			"email: string;",
		}
		for _, s := range mustContain {
			if !strings.Contains(output, s) {
				t.Errorf("missing %q in output:\n%s", s, output)
			}
		}
	})

	t.Run("embedded struct fields flattened", func(t *testing.T) {
		// Base fields should appear in UserOutput, not as a separate Base type.
		if !strings.Contains(output, "id: string;") {
			t.Errorf("embedded Base.ID field missing from UserOutput:\n%s", output)
		}
		if !strings.Contains(output, "createdAt: string;") {
			t.Errorf("time.Time should map to string:\n%s", output)
		}
	})

	t.Run("optional fields", func(t *testing.T) {
		// Pointer field and omitempty field should be optional.
		if !strings.Contains(output, "deletedAt?:") {
			t.Errorf("pointer field should be optional:\n%s", output)
		}
		if !strings.Contains(output, "meta?:") {
			t.Errorf("omitempty field should be optional:\n%s", output)
		}
		if !strings.Contains(output, "tags?:") {
			t.Errorf("omitempty tags should be optional:\n%s", output)
		}
	})

	t.Run("UserInput interface", func(t *testing.T) {
		if !strings.Contains(output, "export interface UserInput {") {
			t.Errorf("missing UserInput interface:\n%s", output)
		}
	})

	t.Run("type mappings", func(t *testing.T) {
		// []string → string[]
		if !strings.Contains(output, "string[]") {
			t.Errorf("[]string should map to string[]:\n%s", output)
		}
		// map[string]string → Record<string, string>
		if !strings.Contains(output, "Record<string, string>") {
			t.Errorf("map[string]string should map to Record<string, string>:\n%s", output)
		}
	})

	t.Run("procedure types", func(t *testing.T) {
		if !strings.Contains(output, "$Mutation<UserInput, UserOutput>") {
			t.Errorf("missing mutation type:\n%s", output)
		}
		if !strings.Contains(output, "$Subscription<void, UserOutput>") {
			t.Errorf("missing subscription type:\n%s", output)
		}
	})

	t.Run("nested namespace", func(t *testing.T) {
		if !strings.Contains(output, "user: {") {
			t.Errorf("missing user namespace:\n%s", output)
		}
	})

	t.Run("list returns array type", func(t *testing.T) {
		if !strings.Contains(output, "$Query<void, UserOutput[]>") {
			t.Errorf("list query should return UserOutput[]:\n%s", output)
		}
	})

	t.Run("AppRouter structure", func(t *testing.T) {
		for _, s := range []string{
			"export type AppRouter =",
			"type AppRouterRecord =",
			"TRPCRouterDef<$RootTypes, AppRouterRecord>",
			"TRPCRouterCaller<$RootTypes, AppRouterRecord>",
		} {
			if !strings.Contains(output, s) {
				t.Errorf("missing %q:\n%s", s, output)
			}
		}
	})
}

func TestGenerateTSNoProcedures(t *testing.T) {
	router := trpcgo.NewRouter()

	outputPath := filepath.Join(t.TempDir(), "trpc.ts")
	if err := router.GenerateTS(outputPath); err != nil {
		t.Fatalf("GenerateTS failed: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}
	output := string(data)

	// Should still produce valid TypeScript with empty router record.
	if !strings.Contains(output, "export type AppRouter =") {
		t.Errorf("empty router should still produce AppRouter type:\n%s", output)
	}
	// Should not contain any interfaces.
	if strings.Contains(output, "export interface") {
		t.Errorf("empty router should not produce interfaces:\n%s", output)
	}
}

func TestGenerateTSVoidInput(t *testing.T) {
	router := trpcgo.NewRouter()
	trpcgo.VoidQuery(router, "ping", func(ctx context.Context) (string, error) {
		return "pong", nil
	})

	outputPath := filepath.Join(t.TempDir(), "trpc.ts")
	if err := router.GenerateTS(outputPath); err != nil {
		t.Fatalf("GenerateTS failed: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}
	output := string(data)

	if !strings.Contains(output, "$Query<void, string>") {
		t.Errorf("expected $Query<void, string>, got:\n%s", output)
	}
	// Should have no interfaces for primitive types.
	if strings.Contains(output, "export interface") {
		t.Errorf("primitive-only procedures should not generate interfaces:\n%s", output)
	}
}

func TestGenerateTSIdempotent(t *testing.T) {
	router := trpcgo.NewRouter()
	trpcgo.VoidQuery(router, "ping", func(ctx context.Context) (string, error) {
		return "pong", nil
	})

	dir := t.TempDir()
	path1 := filepath.Join(dir, "first.ts")
	path2 := filepath.Join(dir, "second.ts")

	if err := router.GenerateTS(path1); err != nil {
		t.Fatal(err)
	}
	if err := router.GenerateTS(path2); err != nil {
		t.Fatal(err)
	}

	data1, _ := os.ReadFile(path1)
	data2, _ := os.ReadFile(path2)

	if string(data1) != string(data2) {
		t.Errorf("GenerateTS is not idempotent:\nfirst:\n%s\nsecond:\n%s", data1, data2)
	}
}

func TestGenerateTSTrackedEventUnwrap(t *testing.T) {
	type Notification struct {
		Message string `json:"message"`
	}

	router := trpcgo.NewRouter()
	trpcgo.VoidSubscribe(router, "notifications", func(ctx context.Context) (<-chan trpcgo.TrackedEvent[Notification], error) {
		return nil, nil
	})

	outputPath := filepath.Join(t.TempDir(), "trpc.ts")
	if err := router.GenerateTS(outputPath); err != nil {
		t.Fatalf("GenerateTS failed: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}
	output := string(data)

	// The subscription output should be Notification, not TrackedEvent.
	if !strings.Contains(output, "$Subscription<void, Notification>") {
		t.Errorf("TrackedEvent should be unwrapped to Notification:\n%s", output)
	}
	if strings.Contains(output, "TrackedEvent") {
		t.Errorf("TrackedEvent should not appear in output:\n%s", output)
	}
	if !strings.Contains(output, "export interface Notification") {
		t.Errorf("Notification interface should be emitted:\n%s", output)
	}
}
