package codegen

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/befabri/trpcgo/internal/analysis"
	"github.com/befabri/trpcgo/internal/typemap"
)

// ProcEntry is a procedure with pre-converted TypeScript type strings.
type ProcEntry struct {
	Path     string
	ProcType string
	InputTS  string
	OutputTS string
}

// GenerateResult holds the output of a generation pass, allowing
// the caller to also generate Zod schemas from the same data.
type GenerateResult struct {
	Procs []ProcEntry
	Defs  []typemap.TypeDef
}

// Generate writes the TypeScript AppRouter definition to w using static analysis results.
func Generate(w io.Writer, result *analysis.Result, metas map[string]typemap.TypeMeta) (*GenerateResult, error) {
	mapper := typemap.NewMapper(metas)

	var procs []ProcEntry
	for _, p := range result.Procedures {
		inputTS := "void"
		if p.InputType != nil {
			inputTS = mapper.Convert(p.InputType)
		}
		outputTS := mapper.Convert(p.OutputType)

		procs = append(procs, ProcEntry{
			Path:     p.Path,
			ProcType: p.Type,
			InputTS:  inputTS,
			OutputTS: outputTS,
		})
	}

	// Resolve type tokens in proc types (handles collision renaming).
	for i := range procs {
		procs[i].InputTS = mapper.Resolve(procs[i].InputTS)
		procs[i].OutputTS = mapper.Resolve(procs[i].OutputTS)
	}

	defs := mapper.Defs()
	if err := WriteAppRouter(w, procs, defs); err != nil {
		return nil, err
	}
	return &GenerateResult{Procs: procs, Defs: defs}, nil
}

// WriteAppRouter writes the complete TypeScript AppRouter file given
// pre-converted procedure entries and interface definitions.
// Used by both static analysis (Generate) and runtime reflection (GenerateTS).
func WriteAppRouter(w io.Writer, procs []ProcEntry, defs []typemap.TypeDef) error {
	// Header.
	fmt.Fprintln(w, "// Code generated by trpcgo. DO NOT EDIT.")
	fmt.Fprintln(w)

	// Type definitions (interfaces, unions, aliases).
	for _, def := range defs {
		writeJSDoc(w, def.Comment, "")
		switch def.Kind {
		case typemap.TypeDefInterface:
			writeInterface(w, def)
		case typemap.TypeDefUnion:
			writeUnion(w, def)
		case typemap.TypeDefAlias:
			writeAlias(w, def)
		}
		fmt.Fprintln(w)
	}

	// Determine which procedure types are used.
	usedTypes := map[string]bool{}
	for _, p := range procs {
		usedTypes[p.ProcType] = true
	}

	// Procedure type helpers (only emit types that are used).
	if len(usedTypes) > 0 {
		fmt.Fprint(w, `// Structural procedure types compatible with @trpc/client
type $Procedure<TType extends string, TInput, TOutput> = {
  _def: {
    $types: { input: TInput; output: TOutput };
    procedure: true;
    type: TType;
    meta: unknown;
    experimental_caller: boolean;
    inputs: any[];
  };
  meta: unknown;
} & ((...args: any[]) => any);

`)
		if usedTypes["query"] {
			fmt.Fprintln(w, `type $Query<TInput, TOutput> = $Procedure<"query", TInput, TOutput>;`)
		}
		if usedTypes["mutation"] {
			fmt.Fprintln(w, `type $Mutation<TInput, TOutput> = $Procedure<"mutation", TInput, TOutput>;`)
		}
		if usedTypes["subscription"] {
			fmt.Fprintln(w, `type $Subscription<TInput, TOutput> = $Procedure<"subscription", TInput, TOutput>;`)
		}
		fmt.Fprintln(w)
	}

	// Build procedure tree from dot-separated paths.
	tree := buildProcTree(procs, func(p ProcEntry) procLeaf {
		return procLeaf{procType: p.ProcType, inputTS: p.InputTS, outputTS: p.OutputTS}
	})

	fmt.Fprint(w, "// Router record matching tRPC's internal structure\ntype AppRouterRecord = ")
	writeTreeNodes(w, tree, 0, func(l procLeaf) string {
		helper := "$Query"
		switch l.procType {
		case "mutation":
			helper = "$Mutation"
		case "subscription":
			helper = "$Subscription"
		}
		return fmt.Sprintf("%s<%s, %s>", helper, l.inputTS, l.outputTS)
	})
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w)

	// AppRouter.
	fmt.Fprint(w, `export type AppRouter = {
  _def: {
    _config: {
      $types: {
        ctx: object;
        meta: object;
        transformer: false;
        errorShape: {
          code: number;
          message: string;
          data: { code: string; httpStatus: number; path?: string };
        };
      };
      transformer: any;
      errorFormatter: any;
      allowOutsideOfServer: boolean;
      isServer: boolean;
      isDev: boolean;
    };
    router: true;
    procedure?: never;
    procedures: AppRouterRecord;
    record: AppRouterRecord;
    lazy: Record<string, never>;
  };
  createCaller: any;
};
`)
	fmt.Fprintln(w)

	// RouterInputs / RouterOutputs.
	writeRouterIO(w, procs)

	return nil
}

// writeRouterIO emits RouterInputs and RouterOutputs type aliases
// matching tRPC's inferRouterInputs<T> / inferRouterOutputs<T>.
func writeRouterIO(w io.Writer, procs []ProcEntry) {
	if len(procs) == 0 {
		return
	}

	identity := func(s string) string { return s }

	inputTree := buildProcTree(procs, func(p ProcEntry) string { return p.InputTS })
	outputTree := buildProcTree(procs, func(p ProcEntry) string { return p.OutputTS })

	fmt.Fprint(w, "export type RouterInputs = ")
	writeTreeNodes(w, inputTree, 0, identity)
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w)

	fmt.Fprint(w, "export type RouterOutputs = ")
	writeTreeNodes(w, outputTree, 0, identity)
	fmt.Fprintln(w, ";")
}

func writeJSDoc(w io.Writer, comment, indent string) {
	if comment == "" {
		return
	}
	lines := strings.Split(comment, "\n")
	if len(lines) == 1 {
		fmt.Fprintf(w, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(w, "%s/**\n", indent)
	for _, line := range lines {
		if line == "" {
			fmt.Fprintf(w, "%s *\n", indent)
		} else {
			fmt.Fprintf(w, "%s * %s\n", indent, line)
		}
	}
	fmt.Fprintf(w, "%s */\n", indent)
}

func writeInterface(w io.Writer, def typemap.TypeDef) {
	typeParams := ""
	if len(def.TypeParams) > 0 {
		typeParams = "<" + strings.Join(def.TypeParams, ", ") + ">"
	}
	fmt.Fprintf(w, "export interface %s%s {\n", def.Name, typeParams)
	for _, f := range def.Fields {
		writeJSDoc(w, f.Comment, "  ")
		opt := ""
		if f.Optional {
			opt = "?"
		}
		prefix := ""
		if f.Readonly {
			prefix = "readonly "
		}
		fmt.Fprintf(w, "  %s%s%s: %s;\n", prefix, f.Name, opt, f.Type)
	}
	fmt.Fprintln(w, "}")
}

func writeUnion(w io.Writer, def typemap.TypeDef) {
	fmt.Fprintf(w, "export type %s = %s;\n", def.Name, strings.Join(def.UnionMembers, " | "))
}

func writeAlias(w io.Writer, def typemap.TypeDef) {
	fmt.Fprintf(w, "export type %s = %s;\n", def.Name, def.AliasOf)
}

// procLeaf holds the data for a procedure tree leaf node.
type procLeaf struct {
	procType string
	inputTS  string
	outputTS string
}

// treeNode is a generic tree node parameterized by leaf data type.
type treeNode[L any] struct {
	children map[string]*treeNode[L]
	isLeaf   bool
	leaf     L
}

// buildProcTree builds a tree from dot-separated procedure paths,
// extracting leaf data from each ProcEntry via leafFn.
func buildProcTree[L any](procs []ProcEntry, leafFn func(ProcEntry) L) *treeNode[L] {
	root := &treeNode[L]{children: make(map[string]*treeNode[L])}
	for _, p := range procs {
		parts := strings.Split(p.Path, ".")
		node := root
		for i, part := range parts {
			child, ok := node.children[part]
			if !ok {
				child = &treeNode[L]{children: make(map[string]*treeNode[L])}
				node.children[part] = child
			}
			if i == len(parts)-1 {
				child.isLeaf = true
				child.leaf = leafFn(p)
			}
			node = child
		}
	}
	return root
}

// writeTreeNodes recursively writes a tree as TypeScript object notation,
// using renderLeaf to format each leaf node.
func writeTreeNodes[L any](w io.Writer, node *treeNode[L], indent int, renderLeaf func(L) string) {
	keys := make([]string, 0, len(node.children))
	for k := range node.children {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	prefix := strings.Repeat("  ", indent)
	fmt.Fprintln(w, "{")
	for _, key := range keys {
		child := node.children[key]
		if child.isLeaf {
			fmt.Fprintf(w, "%s  %s: %s;\n", prefix, key, renderLeaf(child.leaf))
		} else {
			fmt.Fprintf(w, "%s  %s: ", prefix, key)
			writeTreeNodes(w, child, indent+1, renderLeaf)
			fmt.Fprintln(w, ";")
		}
	}
	fmt.Fprintf(w, "%s}", prefix)
}
