package codegen

import (
	"cmp"
	"fmt"
	"io"
	"maps"
	"slices"
	"strings"

	"github.com/befabri/trpcgo/internal/analysis"
	"github.com/befabri/trpcgo/internal/typemap"
)

// ProcEntry is a procedure with pre-converted TypeScript type strings.
type ProcEntry struct {
	Path      string
	ProcType  string
	InputTS   string
	InputZod  string // Concrete schema identity when Go types erase to the same TypeScript type.
	OutputTS  string
	OutputZod string // Concrete Go output identity when public generic arguments erase information.
}

// GenerateResult holds the converted procedures and type definitions of a
// generation pass. The same data feeds the AppRouter, Zod, and enum writers.
type GenerateResult struct {
	Procs []ProcEntry
	Defs  []typemap.TypeDef
}

// Prepare converts static analysis results into codegen entries: procedures
// with TypeScript type strings and the type definitions they reference.
// It performs no I/O; pass the result to [WriteAppRouter], [WriteZodSchemas],
// or [WriteEnums]. validation is the compiled Zod configuration, or nil.
func Prepare(result *analysis.Result, metas map[string]typemap.TypeMeta, validation *typemap.ValidationProgram) *GenerateResult {
	mapper := typemap.NewMapper(metas)
	mapper.SetValidation(validation)

	var procs []ProcEntry
	for _, p := range result.Procedures {
		inputTS, inputZod := "void", "void"
		if p.InputType != nil {
			inputTS = mapper.Convert(p.InputType)
			inputZod = mapper.ConvertZod(p.InputType)
		}
		var outputTS, outputZod string
		if p.Type == "subscription" {
			outputTS = mapper.ConvertSubscriptionOutput(p.OutputType)
			outputZod = mapper.ConvertSubscriptionOutputZod(p.OutputType)
		} else {
			outputTS = mapper.Convert(p.OutputType)
			outputZod = mapper.ConvertZod(p.OutputType)
		}
		if outputZod == outputTS {
			outputZod = ""
		}

		procs = append(procs, ProcEntry{
			Path:      p.Path,
			ProcType:  p.Type,
			InputTS:   inputTS,
			InputZod:  inputZod,
			OutputTS:  outputTS,
			OutputZod: outputZod,
		})
	}

	// Resolve type tokens in proc types (handles collision renaming).
	for i := range procs {
		procs[i].InputTS = mapper.Resolve(procs[i].InputTS)
		procs[i].InputZod = mapper.Resolve(procs[i].InputZod)
		procs[i].OutputTS = mapper.Resolve(procs[i].OutputTS)
		procs[i].OutputZod = mapper.Resolve(procs[i].OutputZod)
	}

	return &GenerateResult{Procs: procs, Defs: mapper.Defs()}
}

// Generate writes the TypeScript AppRouter definition to w using static analysis results.
func Generate(w io.Writer, result *analysis.Result, metas map[string]typemap.TypeMeta, validation *typemap.ValidationProgram) (*GenerateResult, error) {
	gen := Prepare(result, metas, validation)
	if err := WriteAppRouter(w, gen.Procs, gen.Defs); err != nil {
		return nil, err
	}
	return gen, nil
}

// WriteAppRouter writes the complete TypeScript AppRouter file given
// pre-converted procedure entries and interface definitions.
// Used by both static analysis (Generate) and runtime reflection (GenerateTS).
func WriteAppRouter(w io.Writer, procs []ProcEntry, defs []typemap.TypeDef) error {
	procs, defs = publicGoArrayTypes(procs, defs)
	if err := uniqueDefinitionNames(defs); err != nil {
		return err
	}
	ew := newErrWriter(w)

	ew.println("// Code generated by trpcgo. DO NOT EDIT.")
	ew.println("")

	// Determine which procedure types are used.
	usedTypes := map[string]bool{}
	for _, p := range procs {
		usedTypes[p.ProcType] = true
	}

	// Import from @trpc/server (only include types actually used).
	imports := []string{"TRPCRouterDef", "TRPCRouterCaller"}
	if usedTypes["query"] {
		imports = append(imports, "TRPCQueryProcedure")
	}
	if usedTypes["mutation"] {
		imports = append(imports, "TRPCMutationProcedure")
	}
	if usedTypes["subscription"] {
		imports = append(imports, "TRPCSubscriptionProcedure")
	}
	if len(procs) > 0 {
		imports = append(imports, "inferRouterInputs", "inferRouterOutputs")
	}
	slices.Sort(imports)

	ew.println("import type {")
	for _, name := range imports {
		ew.printf("  %s,\n", name)
	}
	ew.println("} from '@trpc/server';")
	ew.println("")

	// Type definitions (interfaces, unions, aliases).
	for _, def := range defs {
		writeTypeDef(ew, def)
	}

	// Procedure type aliases (only emit types that are used).
	if usedTypes["query"] {
		ew.println(`type $Query<TInput, TOutput> = TRPCQueryProcedure<{ input: TInput; output: TOutput; meta: object }>;`)
	}
	if usedTypes["mutation"] {
		ew.println(`type $Mutation<TInput, TOutput> = TRPCMutationProcedure<{ input: TInput; output: TOutput; meta: object }>;`)
	}
	if usedTypes["subscription"] {
		ew.println(`type $Subscription<TInput, TOutput> = TRPCSubscriptionProcedure<{ input: TInput; output: TOutput; meta: object }>;`)
	}
	if len(procs) > 0 {
		ew.println("")
	}

	// Build procedure tree from dot-separated paths.
	tree := buildProcTree(procs, func(p ProcEntry) procLeaf {
		return procLeaf{procType: p.ProcType, inputTS: p.InputTS, outputTS: p.OutputTS}
	})

	ew.print("type AppRouterRecord = ")
	writeTreeNodes(ew, tree, 0, func(l procLeaf) string {
		helper := "$Query"
		switch l.procType {
		case "mutation":
			helper = "$Mutation"
		case "subscription":
			helper = "$Subscription"
		}
		return fmt.Sprintf("%s<%s, %s>", helper, l.inputTS, l.outputTS)
	})
	ew.println(";")
	ew.println("")

	// AppRouter using @trpc/server types.
	ew.print(`type $ErrorShape = { code: number; message: string; data: { code: string; httpStatus: number; path?: string } };
type $RootTypes = { ctx: object; meta: object; errorShape: $ErrorShape; transformer: false };

export type AppRouter = {
  _def: TRPCRouterDef<$RootTypes, AppRouterRecord>;
  createCaller: TRPCRouterCaller<$RootTypes, AppRouterRecord>;
};
`)
	ew.println("")

	// RouterInputs / RouterOutputs via tRPC inference.
	if len(procs) > 0 {
		ew.println("export type RouterInputs = inferRouterInputs<AppRouter>;")
		ew.println("")
		ew.println("export type RouterOutputs = inferRouterOutputs<AppRouter>;")
	}

	return ew.err
}

func writeTypeDef(ew *errWriter, def typemap.TypeDef) {
	writeJSDoc(ew, def.Comment, "")
	switch def.Kind {
	case typemap.TypeDefInterface:
		writeInterface(ew, def)
	case typemap.TypeDefUnion:
		writeUnion(ew, def)
	case typemap.TypeDefAlias:
		writeAlias(ew, def)
	}
	ew.println("")
}

func writeJSDoc(ew *errWriter, comment, indent string) {
	if comment == "" {
		return
	}
	if !strings.Contains(comment, "\n") {
		ew.printf("%s/** %s */\n", indent, comment)
		return
	}
	ew.printf("%s/**\n", indent)
	for line := range strings.SplitSeq(comment, "\n") {
		if line == "" {
			ew.printf("%s *\n", indent)
		} else {
			ew.printf("%s * %s\n", indent, line)
		}
	}
	ew.printf("%s */\n", indent)
}

func writeInterface(ew *errWriter, def typemap.TypeDef) {
	typeParams := typeParameters(def)
	extendsClause := ""
	if len(def.Extends) > 0 {
		extendsClause = " extends " + strings.Join(def.Extends, ", ")
	}
	ew.printf("export interface %s%s%s {\n", def.Name, typeParams, extendsClause)
	for _, f := range def.Fields {
		writeJSDoc(ew, f.Comment, "  ")
		ew.printf("  %s;\n", typemap.PropertyDeclaration(f))
	}
	ew.println("}")
}

func writeUnion(ew *errWriter, def typemap.TypeDef) {
	// Retain literal autocomplete while admitting every value allowed by Go.
	// Named constants are suggestions; validate:"oneof=..." provides closure.
	underlying := enumUnderlyingField(def).Type
	open := underlying
	if underlying == "string" {
		open = "(string & {})"
	}
	// A number intersection cannot serve as a numeric Record index signature.
	members := append(append([]string(nil), def.UnionMembers...), open)
	ew.printf("export type %s = %s;\n", def.Name, strings.Join(members, " | "))
}

func writeAlias(ew *errWriter, def typemap.TypeDef) {
	ew.printf("export type %s%s = %s;\n", def.Name, typeParameters(def), directRecordType(def.AliasOf))
}

// typeParameters renders a generic declaration's parameter list. Each
// parameter keeps the constraint its Go constraint needs, so a mapped-type
// key and a constrained instantiation type-check.
func typeParameters(def typemap.TypeDef) string {
	if len(def.TypeParams) == 0 {
		return ""
	}
	params := make([]string, len(def.TypeParams))
	for i, name := range def.TypeParams {
		params[i] = name
		if i < len(def.TypeParamBounds) && def.TypeParamBounds[i] != "" {
			params[i] += " extends " + def.TypeParamBounds[i]
		}
	}
	return "<" + strings.Join(params, ", ") + ">"
}

// procLeaf holds the data for a procedure tree leaf node.
type procLeaf struct {
	procType string
	inputTS  string
	outputTS string
}

// treeNode is a generic tree node parameterized by leaf data type.
type treeNode[L any] struct {
	children map[string]*treeNode[L]
	isLeaf   bool
	leaf     L
}

// buildProcTree builds a tree from dot-separated procedure paths,
// extracting leaf data from each ProcEntry via leafFn.
func buildProcTree[L any](procs []ProcEntry, leafFn func(ProcEntry) L) *treeNode[L] {
	root := &treeNode[L]{children: make(map[string]*treeNode[L])}
	for _, p := range procs {
		node := root
		for part := range strings.SplitSeq(p.Path, ".") {
			child, ok := node.children[part]
			if !ok {
				child = &treeNode[L]{children: make(map[string]*treeNode[L])}
				node.children[part] = child
			}
			node = child
		}
		node.isLeaf = true
		node.leaf = leafFn(p)
	}
	return root
}

// writeTreeNodes recursively writes a tree as TypeScript object notation,
// using renderLeaf to format each leaf node.
func writeTreeNodes[L any](ew *errWriter, node *treeNode[L], indent int, renderLeaf func(L) string) {
	keys := slices.Sorted(maps.Keys(node.children))

	prefix := strings.Repeat("  ", indent)
	ew.println("{")
	for _, key := range keys {
		child := node.children[key]
		qk := typemap.QuotePropName(key)
		switch {
		case child.isLeaf && len(child.children) > 0:
			// Path is both a leaf and a namespace — emit intersection type.
			ew.printf("%s  %s: %s & ", prefix, qk, renderLeaf(child.leaf))
			writeTreeNodes(ew, child, indent+1, renderLeaf)
			ew.println(";")
		case child.isLeaf:
			ew.printf("%s  %s: %s;\n", prefix, qk, renderLeaf(child.leaf))
		default:
			ew.printf("%s  %s: ", prefix, qk)
			writeTreeNodes(ew, child, indent+1, renderLeaf)
			ew.println(";")
		}
	}
	ew.printf("%s}", prefix)
}

// uniqueDefinitionNames rejects two definitions that would share a generated
// TypeScript name. TypeScript would merge the interfaces and the schema writer
// would keep only one of them, so neither output could be trusted.
func uniqueDefinitionNames(defs []typemap.TypeDef) error {
	seen := make(map[string]string, len(defs))
	for _, def := range defs {
		if other, ok := seen[def.Name]; ok {
			return fmt.Errorf("type name %s is generated for both %s and %s", def.Name, cmp.Or(other, "an earlier definition"), cmp.Or(def.ID, "a later definition"))
		}
		seen[def.Name] = def.ID
	}
	return nil
}

// Go fixed-array decoding materializes zero elements, including nil values in
// nested structs. Public array positions must admit those values so parsed Zod
// data can be passed to a typed tRPC client. Ordinary named structs keep their
// existing declaration; only array positions use the contextual variants.
func publicGoArrayTypes(procs []ProcEntry, defs []typemap.TypeDef) ([]ProcEntry, []typemap.TypeDef) {
	byName := make(map[string]typemap.TypeDef)
	for _, def := range defs {
		byName[def.Name] = def
		for _, instance := range def.Specializations {
			byName[instance.Name] = instance
		}
	}
	all := make(map[string]bool, len(byName))
	for name := range byName {
		all[name] = true
	}
	if !zodNeedsFixedArrays(byName, all) {
		return procs, defs
	}
	// Plan concrete generic identities from the same graph used by schemas.
	// Public TS arguments alone cannot distinguish Box[int] and Box[*int].
	concrete := make(map[string]bool)
	for name, def := range byName {
		if def.InstanceOf != "" {
			concrete[name] = zodNeedsFixedArrays(byName, transitiveReachable(map[string]bool{name: true}, byName))
		}
	}
	variants := make(map[string]typemap.TypeDef)
	var fieldType func(typemap.Field, bool) string
	var definition func(typemap.TypeDef, bool) typemap.TypeDef
	variant := func(name string, context bool) string {
		prefix := "$GoType"
		if context {
			prefix = "$GoArray"
		}
		key := prefix + name
		if _, ok := variants[key]; ok {
			return key
		}
		d := byName[name]
		d.Name = key
		variants[key] = d // register before recursive fields
		variants[key] = definition(d, context)
		return key
	}
	definition = func(def typemap.TypeDef, context bool) typemap.TypeDef {
		def = typemap.ResolveTypeDef(def, nil)
		for i := range def.Fields {
			def.Fields[i].Type = fieldType(def.Fields[i], context)
		}
		if def.Underlying != nil {
			def.AliasOf = fieldType(*def.Underlying, context)
		}
		for i, base := range def.Extends {
			metadata := base
			if i < len(def.ZodExtends) {
				metadata = def.ZodExtends[i]
			}
			partial := strings.HasPrefix(base, "Partial<") && strings.HasSuffix(base, ">")
			if partial {
				base = base[len("Partial<") : len(base)-1]
				metadata = strings.TrimSuffix(strings.TrimPrefix(metadata, "Partial<"), ">")
			}
			base = fieldType(typemap.Field{Type: base, ZodType: metadata}, context)
			if partial {
				base = "Partial<" + base + ">"
			}
			def.Extends[i] = base
		}
		return def
	}
	fieldType = func(field typemap.Field, context bool) string {
		ts := field.Type
		if field.TypeOverride {
			return ts
		}
		if field.Inline != nil {
			d := definition(*field.Inline, context)
			ts = typemap.InlineObjectType(d.Fields)
		} else if element, ok := strings.CutSuffix(ts, "[]"); ok {
			child := publicArrayElement(unwrapZodParentheses(element), field.Element)
			element = fieldType(child, context || field.ArrayLen != nil)
			if len(splitTopLevel(element, '|')) > 1 {
				element = "(" + element + ")"
			}
			ts = element + "[]"
		} else if key, value, ok := zodRecordTypes(ts); ok {
			partial := strings.HasPrefix(ts, "Partial<")
			value = fieldType(publicArrayElement(value, field.Element), context)
			ts = "Record<" + key + ", " + value + ">"
			if partial {
				ts = "Partial<" + ts + ">"
			}
		} else {
			metadata := zodFieldType(field)
			name := metadata
			if _, ok := byName[name]; !ok {
				name = stripGenericArgs(ts)
			}
			if def, ok := byName[name]; ok && def.Kind != typemap.TypeDefUnion {
				if context {
					ts = variant(name, true)
					if def.InstanceOf == "" && len(def.TypeParams) > 0 {
						if index := strings.IndexByte(field.Type, '<'); index >= 0 {
							ts += field.Type[index:]
						}
					}
				} else if concrete[name] {
					ts = variant(name, false)
				}
			}
		}
		if context && ts != "unknown" && goArrayNilEligible(field) {
			ts += " | null"
		}
		return ts
	}
	out := make([]typemap.TypeDef, 0, len(defs))
	for _, def := range defs {
		out = append(out, definition(def, false))
	}
	procs = slices.Clone(procs)
	var procedureType func(string, string) string
	procedureType = func(public, metadata string) string {
		if concrete[metadata] {
			return variant(metadata, false)
		}
		if publicElement, ok := strings.CutSuffix(public, "[]"); ok {
			if metadataElement, ok := strings.CutSuffix(metadata, "[]"); ok {
				return procedureType(unwrapZodParentheses(publicElement), unwrapZodParentheses(metadataElement)) + "[]"
			}
		}
		if key, value, ok := zodRecordTypes(public); ok {
			if _, metadataValue, ok := zodRecordTypes(metadata); ok {
				result := "Record<" + key + ", " + procedureType(value, metadataValue) + ">"
				if strings.HasPrefix(public, "Partial<") {
					result = "Partial<" + result + ">"
				}
				return result
			}
		}
		if fields, ok := inlineTypeFields(public); ok {
			if metadataFields, ok := inlineTypeFields(metadata); ok {
				for i := range fields {
					for _, other := range metadataFields {
						if fields[i].Name == other.Name {
							fields[i].Type = procedureType(fields[i].Type, other.Type)
						}
					}
				}
				return typemap.InlineObjectType(fields)
			}
		}
		return public
	}
	for i := range procs {
		procs[i].InputTS = procedureType(procs[i].InputTS, procs[i].InputZod)
		procs[i].OutputTS = procedureType(procs[i].OutputTS, procs[i].OutputZod)
	}
	for _, name := range slices.Sorted(maps.Keys(variants)) {
		out = append(out, variants[name])
	}
	return procs, out
}

func publicArrayElement(ts string, element *typemap.ElementType) typemap.Field {
	field := zodElementField(ts, element)
	field.ZodType, field.Type = field.Type, ts
	return field
}
