package codegen

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/trpcgo/trpcgo/internal/analysis"
	"github.com/trpcgo/trpcgo/internal/typemap"
)

// ProcEntry is a procedure with pre-converted TypeScript type strings.
type ProcEntry struct {
	Path     string
	ProcType string
	InputTS  string
	OutputTS string
}

// Generate writes the TypeScript AppRouter definition to w using static analysis results.
func Generate(w io.Writer, result *analysis.Result, metas map[string]typemap.TypeMeta) error {
	mapper := typemap.NewMapper(metas)

	var procs []ProcEntry
	for _, p := range result.Procedures {
		inputTS := "void"
		if p.InputType != nil {
			inputTS = mapper.Convert(p.InputType)
		}
		outputTS := mapper.Convert(p.OutputType)

		procs = append(procs, ProcEntry{
			Path:     p.Path,
			ProcType: p.Type,
			InputTS:  inputTS,
			OutputTS: outputTS,
		})
	}

	return WriteAppRouter(w, procs, mapper.Defs())
}

// WriteAppRouter writes the complete TypeScript AppRouter file given
// pre-converted procedure entries and interface definitions.
// Used by both static analysis (Generate) and runtime reflection (GenerateTS).
func WriteAppRouter(w io.Writer, procs []ProcEntry, defs []typemap.TypeDef) error {
	// Header.
	fmt.Fprintln(w, "// Code generated by trpcgo. DO NOT EDIT.")
	fmt.Fprintln(w)

	// Type definitions (interfaces, unions, aliases).
	for _, def := range defs {
		writeJSDoc(w, def.Comment, "")
		switch def.Kind {
		case typemap.TypeDefInterface:
			writeInterface(w, def)
		case typemap.TypeDefUnion:
			writeUnion(w, def)
		case typemap.TypeDefAlias:
			writeAlias(w, def)
		}
		fmt.Fprintln(w)
	}

	// Procedure type helpers.
	fmt.Fprint(w, `// Structural procedure types compatible with @trpc/client
type $Procedure<TType extends string, TInput, TOutput> = {
  _def: {
    $types: { input: TInput; output: TOutput };
    procedure: true;
    type: TType;
    meta: unknown;
    experimental_caller: boolean;
    inputs: any[];
  };
  meta: unknown;
} & ((...args: any[]) => any);

type $Query<TInput, TOutput> = $Procedure<"query", TInput, TOutput>;
type $Mutation<TInput, TOutput> = $Procedure<"mutation", TInput, TOutput>;
type $Subscription<TInput, TOutput> = $Procedure<"subscription", TInput, TOutput>;

`)

	// Build procedure tree from dot-separated paths.
	tree := buildTree(procs)

	fmt.Fprint(w, "// Router record matching tRPC's internal structure\ntype AppRouterRecord = ")
	writeTree(w, tree, 0)
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w)

	// AppRouter.
	fmt.Fprint(w, `export type AppRouter = {
  _def: {
    _config: {
      $types: {
        ctx: object;
        meta: object;
        transformer: false;
        errorShape: {
          code: number;
          message: string;
          data: { code: string; httpStatus: number; path?: string };
        };
      };
      transformer: any;
      errorFormatter: any;
      allowOutsideOfServer: boolean;
      isServer: boolean;
      isDev: boolean;
    };
    router: true;
    procedure?: never;
    procedures: AppRouterRecord;
    record: AppRouterRecord;
    lazy: Record<string, never>;
  };
  createCaller: any;
};
`)

	return nil
}

func writeJSDoc(w io.Writer, comment, indent string) {
	if comment == "" {
		return
	}
	lines := strings.Split(comment, "\n")
	if len(lines) == 1 {
		fmt.Fprintf(w, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(w, "%s/**\n", indent)
	for _, line := range lines {
		if line == "" {
			fmt.Fprintf(w, "%s *\n", indent)
		} else {
			fmt.Fprintf(w, "%s * %s\n", indent, line)
		}
	}
	fmt.Fprintf(w, "%s */\n", indent)
}

func writeInterface(w io.Writer, def typemap.TypeDef) {
	typeParams := ""
	if len(def.TypeParams) > 0 {
		typeParams = "<" + strings.Join(def.TypeParams, ", ") + ">"
	}
	fmt.Fprintf(w, "export interface %s%s {\n", def.Name, typeParams)
	for _, f := range def.Fields {
		writeJSDoc(w, f.Comment, "  ")
		opt := ""
		if f.Optional {
			opt = "?"
		}
		prefix := ""
		if f.Readonly {
			prefix = "readonly "
		}
		fmt.Fprintf(w, "  %s%s%s: %s;\n", prefix, f.Name, opt, f.Type)
	}
	fmt.Fprintln(w, "}")
}

func writeUnion(w io.Writer, def typemap.TypeDef) {
	fmt.Fprintf(w, "export type %s = %s;\n", def.Name, strings.Join(def.UnionMembers, " | "))
}

func writeAlias(w io.Writer, def typemap.TypeDef) {
	fmt.Fprintf(w, "export type %s = %s;\n", def.Name, def.AliasOf)
}

type treeNode struct {
	children map[string]*treeNode
	isLeaf   bool
	procType string
	inputTS  string
	outputTS string
}

func buildTree(procs []ProcEntry) *treeNode {
	root := &treeNode{children: make(map[string]*treeNode)}

	for _, p := range procs {
		parts := strings.Split(p.Path, ".")
		node := root
		for i, part := range parts {
			if node.children == nil {
				node.children = make(map[string]*treeNode)
			}
			child, ok := node.children[part]
			if !ok {
				child = &treeNode{children: make(map[string]*treeNode)}
				node.children[part] = child
			}
			if i == len(parts)-1 {
				child.isLeaf = true
				child.procType = p.ProcType
				child.inputTS = p.InputTS
				child.outputTS = p.OutputTS
			}
			node = child
		}
	}

	return root
}

func writeTree(w io.Writer, node *treeNode, indent int) {
	keys := make([]string, 0, len(node.children))
	for k := range node.children {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	prefix := strings.Repeat("  ", indent)
	fmt.Fprintln(w, "{")
	for _, key := range keys {
		child := node.children[key]
		if child.isLeaf {
			helper := "$Query"
			switch child.procType {
			case "mutation":
				helper = "$Mutation"
			case "subscription":
				helper = "$Subscription"
			}
			fmt.Fprintf(w, "%s  %s: %s<%s, %s>;\n", prefix, key, helper, child.inputTS, child.outputTS)
		} else {
			fmt.Fprintf(w, "%s  %s: ", prefix, key)
			writeTree(w, child, indent+1)
			fmt.Fprintln(w, ";")
		}
	}
	fmt.Fprintf(w, "%s}", prefix)
}
