package codegen

import (
	"fmt"
	"io"
	"strconv"

	"github.com/befabri/trpcgo/internal/typemap"
)

// WriteEnums writes runtime `as const` objects for named string enum unions.
// Numeric unions are skipped because the analyzer does not retain const names.
func WriteEnums(w io.Writer, defs []typemap.TypeDef) error {
	ew := newErrWriter(w)
	ew.println("// Code generated by trpcgo. DO NOT EDIT.")

	for _, def := range defs {
		if !def.IsStringUnion() {
			continue
		}
		ew.println("")
		writeJSDoc(ew, def.Comment, "")
		writeEnumObject(ew, def)
	}

	return ew.err
}

func writeEnumObject(ew *errWriter, def typemap.TypeDef) {
	ew.printf("export const %sEnum = {\n", def.Name)
	seen := make(map[string]bool, len(def.UnionMembers))
	for _, member := range def.UnionMembers {
		if seen[member] {
			continue
		}
		seen[member] = true
		ew.printf("  %s: %s,\n", enumKey(member), member)
	}
	ew.println("} as const;")
}

func enumKey(member string) string {
	raw, err := strconv.Unquote(member)
	if err != nil {
		return member
	}
	if raw == "__proto__" {
		// In object literals, __proto__ is a setter unless it is computed.
		return fmt.Sprintf("[%q]", raw)
	}
	return typemap.QuotePropName(raw)
}
