package codegen_test

import (
	"bytes"
	"errors"
	"strings"
	"testing"

	"github.com/befabri/trpcgo/internal/analysis"
	"github.com/befabri/trpcgo/internal/codegen"
	"github.com/befabri/trpcgo/internal/typemap"
)

func writeEnums(t *testing.T, defs []typemap.TypeDef) string {
	t.Helper()
	var buf bytes.Buffer
	if err := codegen.WriteEnums(&buf, defs); err != nil {
		t.Fatal(err)
	}
	return buf.String()
}

type failingWriter struct {
	err error
}

func (w failingWriter) Write([]byte) (int, error) {
	return 0, w.err
}

func TestWriteEnumsEndToEnd(t *testing.T) {
	dir := testdataDir("crosspkg")
	result, err := analysis.Analyze([]string{"."}, dir)
	if err != nil {
		t.Fatal(err)
	}
	var trpcBuf bytes.Buffer
	gen, err := codegen.Generate(&trpcBuf, result, result.TypeMetas)
	if err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	if err := codegen.WriteEnums(&buf, gen.Defs); err != nil {
		t.Fatal(err)
	}
	output := buf.String()

	for _, want := range []string{
		"export const RoleEnum = {",
		`viewer: "viewer",`,
		"export const StatusEnum = {",
		`PENDING: "PENDING",`,
		"export const PhaseEnum = {",
		`queued: "queued",`,
	} {
		if !strings.Contains(output, want) {
			t.Errorf("end-to-end output missing %q:\n%s", want, output)
		}
	}

	if strings.Contains(output, "DurationEnum") {
		t.Errorf("stdlib Duration leaked an enum object:\n%s", output)
	}
}

func TestWriteEnumsReturnsWriteError(t *testing.T) {
	writeErr := errors.New("write failed")
	err := codegen.WriteEnums(failingWriter{err: writeErr}, []typemap.TypeDef{
		{Name: "Role", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"admin"`}},
	})
	if !errors.Is(err, writeErr) {
		t.Fatalf("WriteEnums error = %v, want wrapping %v", err, writeErr)
	}
}

func TestWriteEnumsStringUnion(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Role",
			Kind:         typemap.TypeDefUnion,
			UnionMembers: []string{`"viewer"`, `"admin"`, `"owner"`},
		},
	}
	output := writeEnums(t, defs)

	want := "export const RoleEnum = {\n  viewer: \"viewer\",\n  admin: \"admin\",\n  owner: \"owner\",\n} as const;"
	if !strings.Contains(output, want) {
		t.Errorf("string enum object mismatch.\nwant:\n%s\ngot:\n%s", want, output)
	}
	if !strings.HasPrefix(output, "// Code generated by trpcgo. DO NOT EDIT.") {
		t.Errorf("missing DO NOT EDIT header.\ngot:\n%s", output)
	}
}

func TestWriteEnumsOrderMatchesUnion(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Status",
			Kind:         typemap.TypeDefUnion,
			UnionMembers: []string{`"PENDING"`, `"RUNNING"`, `"DONE"`, `"FAILED"`},
		},
	}
	output := writeEnums(t, defs)

	idx := []int{
		strings.Index(output, "PENDING:"),
		strings.Index(output, "RUNNING:"),
		strings.Index(output, "DONE:"),
		strings.Index(output, "FAILED:"),
	}
	for i := 1; i < len(idx); i++ {
		if idx[i-1] < 0 || idx[i] < 0 || idx[i-1] >= idx[i] {
			t.Errorf("members out of order: %v\noutput:\n%s", idx, output)
		}
	}
}

func TestWriteEnumsSkipsNumericUnion(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Priority",
			Kind:         typemap.TypeDefUnion,
			UnionMembers: []string{"1", "2", "3"},
		},
	}
	output := writeEnums(t, defs)

	if strings.Contains(output, "PriorityEnum") {
		t.Errorf("numeric enum should be skipped, got:\n%s", output)
	}
}

func TestWriteEnumsSkipsNonUnion(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "User", Kind: typemap.TypeDefInterface},
		{Name: "Email", Kind: typemap.TypeDefAlias, AliasOf: "string"},
	}
	output := writeEnums(t, defs)

	if strings.Contains(output, "Enum") {
		t.Errorf("non-union defs should be skipped, got:\n%s", output)
	}
}

func TestWriteEnumsSingleMember(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Kind",
			Kind:         typemap.TypeDefUnion,
			UnionMembers: []string{`"only"`},
		},
	}
	output := writeEnums(t, defs)

	want := "export const KindEnum = {\n  only: \"only\",\n} as const;"
	if !strings.Contains(output, want) {
		t.Errorf("single-member enum mismatch.\nwant:\n%s\ngot:\n%s", want, output)
	}
}

func TestWriteEnumsEmitsJSDoc(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Role",
			Kind:         typemap.TypeDefUnion,
			Comment:      "Role is a permission level.",
			UnionMembers: []string{`"admin"`},
		},
	}
	output := writeEnums(t, defs)

	if !strings.Contains(output, "/** Role is a permission level. */") {
		t.Errorf("type comment should carry over as JSDoc, got:\n%s", output)
	}
}

func TestWriteEnumsMixedDefs(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "User", Kind: typemap.TypeDefInterface},
		{Name: "Role", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"admin"`, `"viewer"`}},
		{Name: "Email", Kind: typemap.TypeDefAlias, AliasOf: "string"},
		{Name: "Priority", Kind: typemap.TypeDefUnion, UnionMembers: []string{"1", "2"}},
	}
	output := writeEnums(t, defs)

	if !strings.Contains(output, "export const RoleEnum = {") {
		t.Errorf("string union should be emitted:\n%s", output)
	}
	for _, notWant := range []string{"UserEnum", "EmailEnum", "PriorityEnum"} {
		if strings.Contains(output, notWant) {
			t.Errorf("unexpected %s emitted:\n%s", notWant, output)
		}
	}
}

func TestWriteEnumsFallbackOnUnparsableMember(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Broken",
			Kind:         typemap.TypeDefUnion,
			UnionMembers: []string{`"unterminated`},
		},
	}
	output := writeEnums(t, defs)

	if !strings.Contains(output, `"unterminated: "unterminated,`) {
		t.Errorf("expected verbatim fallback key, got:\n%s", output)
	}
}

func TestWriteEnumsQuotesNonIdentifierValues(t *testing.T) {
	defs := []typemap.TypeDef{
		{
			Name:         "Event",
			Kind:         typemap.TypeDefUnion,
			UnionMembers: []string{`"user.created"`, `"user-deleted"`},
		},
	}
	output := writeEnums(t, defs)

	for _, want := range []string{`"user.created": "user.created",`, `"user-deleted": "user-deleted",`} {
		if !strings.Contains(output, want) {
			t.Errorf("missing quoted key %q in:\n%s", want, output)
		}
	}
}

func TestWriteEnumsEmptyDefs(t *testing.T) {
	output := writeEnums(t, nil)

	if !strings.HasPrefix(output, "// Code generated by trpcgo. DO NOT EDIT.") {
		t.Errorf("expected header, got:\n%s", output)
	}
	if strings.Contains(output, "export const") {
		t.Errorf("no defs should yield no objects:\n%s", output)
	}
}

func TestWriteEnumsMultipleStringUnions(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Role", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"admin"`}},
		{Name: "Status", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"on"`, `"off"`}},
	}
	output := writeEnums(t, defs)

	if !strings.Contains(output, "export const RoleEnum = {") || !strings.Contains(output, "export const StatusEnum = {") {
		t.Errorf("both enums should be emitted:\n%s", output)
	}
	if n := strings.Count(output, "} as const;"); n != 2 {
		t.Errorf("expected two closed objects, found %d:\n%s", n, output)
	}
}

func TestWriteEnumsDeduplicatesRepeatedValues(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Color", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"red"`, `"red"`, `"blue"`}},
	}
	output := writeEnums(t, defs)

	if n := strings.Count(output, `red: "red",`); n != 1 {
		t.Errorf("duplicate value should be emitted once, found %d:\n%s", n, output)
	}
	if !strings.Contains(output, `blue: "blue",`) {
		t.Errorf("missing distinct value blue:\n%s", output)
	}
}

func TestWriteEnumsEscapesSpecialValues(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Tok", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"a\"b"`, `"c\\d"`}},
	}
	output := writeEnums(t, defs)

	for _, want := range []string{`"a\"b": "a\"b",`, `"c\\d": "c\\d",`} {
		if !strings.Contains(output, want) {
			t.Errorf("missing escaped entry %q:\n%s", want, output)
		}
	}
}

func TestWriteEnumsEmptyStringMember(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "E", Kind: typemap.TypeDefUnion, UnionMembers: []string{`""`, `"x"`}},
	}
	output := writeEnums(t, defs)

	if !strings.Contains(output, `"": "",`) {
		t.Errorf("empty-string member should map to an empty quoted key:\n%s", output)
	}
}

func TestWriteEnumsLeadingDigitValue(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "V", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"3d"`, `"hd"`}},
	}
	output := writeEnums(t, defs)

	if !strings.Contains(output, `"3d": "3d",`) {
		t.Errorf("leading-digit value should be a quoted key:\n%s", output)
	}
	if !strings.Contains(output, `hd: "hd",`) {
		t.Errorf("identifier value should be an unquoted key:\n%s", output)
	}
}

func TestWriteEnumsReservedWordKey(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Kw", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"default"`, `"class"`}},
	}
	output := writeEnums(t, defs)

	for _, want := range []string{`default: "default",`, `class: "class",`} {
		if !strings.Contains(output, want) {
			t.Errorf("reserved word should be an unquoted key %q:\n%s", want, output)
		}
	}
}

func TestWriteEnumsProtoKeyUsesComputedProperty(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Danger", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"__proto__"`, `"constructor"`}},
	}
	output := writeEnums(t, defs)

	for _, want := range []string{`["__proto__"]: "__proto__",`, `constructor: "constructor",`} {
		if !strings.Contains(output, want) {
			t.Errorf("missing safe key %q in:\n%s", want, output)
		}
	}
}

func TestWriteEnumsSkipsEmptyUnionMembers(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Empty", Kind: typemap.TypeDefUnion, UnionMembers: nil},
		{Name: "Role", Kind: typemap.TypeDefUnion, UnionMembers: []string{`"a"`}},
	}
	output := writeEnums(t, defs)

	if strings.Contains(output, "EmptyEnum") {
		t.Errorf("a union with no members should be skipped:\n%s", output)
	}
	if !strings.Contains(output, "RoleEnum") {
		t.Errorf("a populated union should still emit:\n%s", output)
	}
}

func TestWriteEnumsSkipsNegativeAndFloatUnions(t *testing.T) {
	defs := []typemap.TypeDef{
		{Name: "Neg", Kind: typemap.TypeDefUnion, UnionMembers: []string{"-1", "0", "1"}},
		{Name: "Frac", Kind: typemap.TypeDefUnion, UnionMembers: []string{"1.5", "2.5"}},
	}
	output := writeEnums(t, defs)

	for _, notWant := range []string{"NegEnum", "FracEnum"} {
		if strings.Contains(output, notWant) {
			t.Errorf("non-string union %s should be skipped:\n%s", notWant, output)
		}
	}
}
