package codegen

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/befabri/trpcgo/internal/typemap"
)

// WriteEnums writes runtime `as const` objects for named string enum unions.
// Numeric unions are skipped because the analyzer does not retain const names.
func WriteEnums(w io.Writer, defs []typemap.TypeDef) error {
	if _, err := fmt.Fprintln(w, "// Code generated by trpcgo. DO NOT EDIT."); err != nil {
		return err
	}

	for _, def := range defs {
		if !def.IsStringUnion() {
			continue
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
		if err := writeEnumJSDoc(w, def.Comment); err != nil {
			return err
		}
		if err := writeEnumObject(w, def); err != nil {
			return err
		}
	}

	return nil
}

func writeEnumJSDoc(w io.Writer, comment string) error {
	if comment == "" {
		return nil
	}
	lines := strings.Split(comment, "\n")
	if len(lines) == 1 {
		_, err := fmt.Fprintf(w, "/** %s */\n", lines[0])
		return err
	}
	if _, err := fmt.Fprintln(w, "/**"); err != nil {
		return err
	}
	for _, line := range lines {
		if line == "" {
			if _, err := fmt.Fprintln(w, " *"); err != nil {
				return err
			}
		} else if _, err := fmt.Fprintf(w, " * %s\n", line); err != nil {
			return err
		}
	}
	_, err := fmt.Fprintln(w, " */")
	return err
}

func writeEnumObject(w io.Writer, def typemap.TypeDef) error {
	if _, err := fmt.Fprintf(w, "export const %sEnum = {\n", def.Name); err != nil {
		return err
	}
	seen := make(map[string]bool, len(def.UnionMembers))
	for _, member := range def.UnionMembers {
		if seen[member] {
			continue
		}
		seen[member] = true
		if _, err := fmt.Fprintf(w, "  %s: %s,\n", enumKey(member), member); err != nil {
			return err
		}
	}
	_, err := fmt.Fprintln(w, "} as const;")
	return err
}

func enumKey(member string) string {
	raw, err := strconv.Unquote(member)
	if err != nil {
		return member
	}
	if raw == "__proto__" {
		// In object literals, __proto__ is a setter unless it is computed.
		return fmt.Sprintf("[%q]", raw)
	}
	return typemap.QuotePropName(raw)
}
