package codegen

import (
	"fmt"
	"io"
	"sort"
	"github.com/befabri/trpcgo/internal/analysis"
	"github.com/befabri/trpcgo/internal/typemap"
)

// GenerateORPC writes the oRPC RouterClient type definition to w using static
// analysis results. Returns a GenerateResult for optional Zod generation.
func GenerateORPC(w io.Writer, result *analysis.Result, metas map[string]typemap.TypeMeta) (*GenerateResult, error) {
	mapper := typemap.NewMapper(metas)

	var procs []ProcEntry
	for _, p := range result.Procedures {
		inputTS := "void"
		if p.InputType != nil {
			inputTS = mapper.Convert(p.InputType)
		}
		outputTS := mapper.Convert(p.OutputType)

		procs = append(procs, ProcEntry{
			Path:     p.Path,
			ProcType: p.Type,
			InputTS:  inputTS,
			OutputTS: outputTS,
		})
	}

	// Resolve type tokens.
	for i := range procs {
		procs[i].InputTS = mapper.Resolve(procs[i].InputTS)
		procs[i].OutputTS = mapper.Resolve(procs[i].OutputTS)
	}

	defs := mapper.Defs()
	if err := WriteORPCRouter(w, procs, defs); err != nil {
		return nil, err
	}
	return &GenerateResult{Procs: procs, Defs: defs}, nil
}

// WriteORPCRouter writes the complete oRPC RouterClient TypeScript file.
func WriteORPCRouter(w io.Writer, procs []ProcEntry, defs []typemap.TypeDef) error {
	_, _ = fmt.Fprintln(w, "// Code generated by trpcgo. DO NOT EDIT.")
	_, _ = fmt.Fprintln(w)

	// Import from @orpc/client.
	var imports []string
	imports = append(imports, "Client")
	if len(procs) > 0 {
		imports = append(imports, "InferClientInputs", "InferClientOutputs")
	}
	// Check if any subscription procedures exist (they use AsyncIterator output).
	hasSubscriptions := false
	for _, p := range procs {
		if p.ProcType == "subscription" {
			hasSubscriptions = true
			break
		}
	}
	_ = hasSubscriptions
	sort.Strings(imports)

	_, _ = fmt.Fprintln(w, "import type {")
	for _, name := range imports {
		_, _ = fmt.Fprintf(w, "  %s,\n", name)
	}
	_, _ = fmt.Fprintln(w, "} from '@orpc/client';")
	_, _ = fmt.Fprintln(w)

	// Type definitions (shared with tRPC codegen).
	for _, def := range defs {
		writeJSDoc(w, def.Comment, "")
		switch def.Kind {
		case typemap.TypeDefInterface:
			writeInterface(w, def)
		case typemap.TypeDefUnion:
			writeUnion(w, def)
		case typemap.TypeDefAlias:
			writeAlias(w, def)
		}
		_, _ = fmt.Fprintln(w)
	}

	// Procedure helper type.
	// oRPC Client<TClientContext, TInput, TOutput, TError>.
	// For subscriptions, output is wrapped in AsyncIteratorObject.
	_, _ = fmt.Fprintln(w, `type $Proc<TInput, TOutput> = Client<Record<never, never>, TInput, TOutput, Error>;`)
	_, _ = fmt.Fprintln(w, `type $Sub<TInput, TOutput> = Client<Record<never, never>, TInput, AsyncIteratorObject<TOutput>, Error>;`)
	_, _ = fmt.Fprintln(w)

	// Build procedure tree.
	tree := buildProcTree(procs, func(p ProcEntry) procLeaf {
		return procLeaf{procType: p.ProcType, inputTS: p.InputTS, outputTS: p.OutputTS}
	})

	_, _ = fmt.Fprint(w, "export type RouterClient = ")
	writeTreeNodes(w, tree, 0, func(l procLeaf) string {
		helper := "$Proc"
		if l.procType == "subscription" {
			helper = "$Sub"
		}
		return fmt.Sprintf("%s<%s, %s>", helper, l.inputTS, l.outputTS)
	})
	_, _ = fmt.Fprintln(w, ";")
	_, _ = fmt.Fprintln(w)

	// Inference helpers.
	if len(procs) > 0 {
		_, _ = fmt.Fprintln(w, "export type RouterInputs = InferClientInputs<RouterClient>;")
		_, _ = fmt.Fprintln(w)
		_, _ = fmt.Fprintln(w, "export type RouterOutputs = InferClientOutputs<RouterClient>;")
	}

	return nil
}

// WriteORPCContract writes an OpenAPI-compatible contract from procedures.
// This is a placeholder for future OpenAPI spec generation.
func WriteORPCContract(w io.Writer, procs []ProcEntry, defs []typemap.TypeDef) error {
	// TODO: generate OpenAPI 3.1 spec from procedure metadata + types.
	_, _ = fmt.Fprintf(w, "// OpenAPI spec generation not yet implemented.\n")
	return nil
}

