package codegen

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/befabri/trpcgo/internal/typemap"
)

// WriteZodSchemas writes Zod 4 validation schemas for all procedure input types
// and their transitive dependencies.
func WriteZodSchemas(w io.Writer, procs []ProcEntry, defs []typemap.TypeDef, style typemap.ZodStyle) error {
	// Collect all input type names from procedures.
	inputTypeNames := make(map[string]bool)
	for _, p := range procs {
		if p.InputTS != "void" {
			// Extract the top-level type name (strip generic args).
			name := stripGenericArgs(p.InputTS)
			inputTypeNames[name] = true
		}
	}

	if len(inputTypeNames) == 0 {
		return nil
	}

	// Build dependency graph and find reachable types.
	defsByName := make(map[string]typemap.TypeDef)
	for _, d := range defs {
		defsByName[d.Name] = d
	}

	reachable := transitiveReachable(inputTypeNames, defsByName)

	// Topological sort for correct emit order (dependencies before dependents).
	plan := topologicalSort(reachable, defsByName)

	// Header.
	_, _ = fmt.Fprintln(w, "// Code generated by trpcgo. DO NOT EDIT.")
	_, _ = fmt.Fprintln(w)

	if style == typemap.ZodMini {
		_, _ = fmt.Fprintln(w, `import * as z from "zod/mini";`)
	} else {
		_, _ = fmt.Fprintln(w, `import { z } from "zod";`)
	}
	_, _ = fmt.Fprintln(w)

	// Emit schemas in dependency order.
	for _, name := range plan.Order {
		def, ok := defsByName[name]
		if !ok {
			continue
		}
		writeZodSchema(w, def, plan.Cycles, style)
		_, _ = fmt.Fprintln(w)
	}

	return nil
}

// writeZodSchema emits a single Zod schema definition.
func writeZodSchema(w io.Writer, def typemap.TypeDef, cycles map[string]map[string]bool, style typemap.ZodStyle) {
	switch def.Kind {
	case typemap.TypeDefInterface:
		writeZodObject(w, def, cycles, style)
	case typemap.TypeDefUnion:
		writeZodEnum(w, def)
	case typemap.TypeDefAlias:
		writeZodAlias(w, def, style)
	}
}

func writeZodObject(w io.Writer, def typemap.TypeDef, cycles map[string]map[string]bool, style typemap.ZodStyle) {
	schemaName := def.Name + "Schema"
	isCyclic := len(cycles[def.Name]) > 0
	hasExtends := len(def.Extends) > 0

	// Build the schema expression opener.
	// Without extends: z.object({...})
	// With extends: BaseSchema.extend({...})
	var objectExpr string
	if hasExtends {
		objectExpr = extendsBaseExpr(def.Extends) + ".extend({"
	} else {
		objectExpr = "z.object({"
	}

	if isCyclic {
		_, _ = fmt.Fprintf(w, "export const %s: z.ZodType<%s> = z.lazy(() => %s\n", schemaName, def.Name, objectExpr)
	} else {
		_, _ = fmt.Fprintf(w, "export const %s = %s\n", schemaName, objectExpr)
	}

	for _, f := range def.Fields {
		zodType := fieldToZod(f, cycles[def.Name], style)
		_, _ = fmt.Fprintf(w, "  %s: %s,\n", typemap.QuotePropName(f.Name), zodType)
	}

	if isCyclic {
		_, _ = fmt.Fprintln(w, "}));")
	} else {
		_, _ = fmt.Fprintln(w, "});")
	}
}

// extendsBaseExpr builds the Zod base expression for extends.
// Single: "BaseSchema" or "BaseSchema.partial()" for Partial<Base>
// Multiple: "Base1Schema.merge(Base2Schema)"
func extendsBaseExpr(extends []string) string {
	parts := make([]string, len(extends))
	for i, ext := range extends {
		if after, ok := strings.CutPrefix(ext, "Partial<"); ok {
			name := strings.TrimSuffix(after, ">")
			parts[i] = name + "Schema.partial()"
		} else {
			parts[i] = ext + "Schema"
		}
	}
	if len(parts) == 1 {
		return parts[0]
	}
	result := parts[0]
	for _, p := range parts[1:] {
		result += ".merge(" + p + ")"
	}
	return result
}

func writeZodEnum(w io.Writer, def typemap.TypeDef) {
	schemaName := def.Name + "Schema"

	// z.enum() only accepts string literals. For non-string unions (integers),
	// emit z.union([z.literal(1), z.literal(2), ...]) instead.
	// We check the first member: Go const groups are homogeneous, so all
	// members share the same underlying type (all strings or all ints).
	if len(def.UnionMembers) > 0 && !strings.HasPrefix(def.UnionMembers[0], `"`) {
		literals := make([]string, len(def.UnionMembers))
		for i, m := range def.UnionMembers {
			literals[i] = "z.literal(" + m + ")"
		}
		_, _ = fmt.Fprintf(w, "export const %s = z.union([%s]);\n", schemaName, strings.Join(literals, ", "))
		return
	}

	_, _ = fmt.Fprintf(w, "export const %s = z.enum([%s]);\n", schemaName, strings.Join(def.UnionMembers, ", "))
}

func writeZodAlias(w io.Writer, def typemap.TypeDef, style typemap.ZodStyle) {
	schemaName := def.Name + "Schema"
	base := typemap.ZodBaseForTSType(def.AliasOf, "")
	if base == "" {
		base = "z.unknown()"
	}
	f := typemap.Field{Type: def.AliasOf}
	zodStr := typemap.ZodType(f, style)
	if zodStr == "" {
		zodStr = base
	}
	_, _ = fmt.Fprintf(w, "export const %s = %s;\n", schemaName, zodStr)
}

// fieldToZod converts a single field to its Zod representation.
func fieldToZod(f typemap.Field, cyclicFields map[string]bool, style typemap.ZodStyle) string {
	// Check if there's a base type directly from validate tags + Go kind.
	base := typemap.ZodBaseForTSType(f.Type, f.GoKind)

	if base != "" {
		// Primitive or known type — use ZodType for full constraint chain.
		return typemap.ZodType(f, style)
	}

	// Complex types.
	tsType := f.Type

	// Array: "Foo[]" → z.array(FooSchema)
	if before, ok := strings.CutSuffix(tsType, "[]"); ok {
		elemType := before
		elemType = strings.TrimPrefix(elemType, "(")
		elemType = strings.TrimSuffix(elemType, ")")

		// Build element schema, applying dive rules if present.
		var elemZod string
		if len(f.ElementValidate) > 0 && f.ElementGoKind != "" && f.ElementGoKind != "struct" {
			// Create a virtual field for the element with dive rules.
			elemField := typemap.Field{
				Type:     elemType,
				GoKind:   f.ElementGoKind,
				Validate: f.ElementValidate,
			}
			elemZod = typemap.ZodType(elemField, style)
		}
		if elemZod == "" {
			elemZod = tsTypeToZodRef(elemType, f.ElementGoKind)
		}

		result := fmt.Sprintf("z.array(%s)", elemZod)

		// Apply container-level constraints (before dive: min/max = array length).
		for _, rule := range f.Validate {
			switch rule.Tag {
			case "min":
				if rule.Param != "" {
					result += fmt.Sprintf(".min(%s)", rule.Param)
				}
			case "max":
				if rule.Param != "" {
					result += fmt.Sprintf(".max(%s)", rule.Param)
				}
			case "len":
				if rule.Param != "" {
					result += fmt.Sprintf(".length(%s)", rule.Param)
				}
			}
		}

		if f.Optional {
			if style == typemap.ZodMini {
				result = fmt.Sprintf("z.optional(%s)", result)
			} else {
				result += ".optional()"
			}
		}
		return result
	}

	// Record: "Record<K, V>" → z.record(K, V)
	if strings.HasPrefix(tsType, "Record<") {
		inner := tsType[len("Record<") : len(tsType)-1]
		parts := splitTopLevel(inner, ',')
		if len(parts) == 2 {
			keyZod := tsTypeToZodRef(strings.TrimSpace(parts[0]), "")
			valZod := tsTypeToZodRef(strings.TrimSpace(parts[1]), "")
			result := fmt.Sprintf("z.record(%s, %s)", keyZod, valZod)
			if f.Optional {
				if style == typemap.ZodMini {
					result = fmt.Sprintf("z.optional(%s)", result)
				} else {
					result += ".optional()"
				}
			}
			return result
		}
	}

	// Named type reference: "Foo" → FooSchema
	// Check for cyclic reference — use getter syntax.
	refName := stripGenericArgs(tsType)
	ref := refName + "Schema"

	// Cyclic references work because the parent schema uses z.lazy(),
	// which defers evaluation until runtime. The ref is just the schema name.

	if f.Optional {
		if style == typemap.ZodMini {
			return fmt.Sprintf("z.optional(%s)", ref)
		}
		return ref + ".optional()"
	}
	return ref
}

// tsTypeToZodRef converts a TS type string to a Zod reference (for array/record elements).
func tsTypeToZodRef(tsType, goKind string) string {
	base := typemap.ZodBaseForTSType(tsType, goKind)
	if base != "" {
		return base
	}
	// Named type → Schema reference.
	return stripGenericArgs(tsType) + "Schema"
}

// stripGenericArgs removes generic type arguments: "Foo<Bar>" → "Foo"
func stripGenericArgs(s string) string {
	if before, _, ok := strings.Cut(s, "<"); ok {
		return before
	}
	return s
}

// splitTopLevel splits a string by sep, respecting angle brackets.
func splitTopLevel(s string, sep byte) []string {
	var parts []string
	depth := 0
	start := 0
	for i := range len(s) {
		switch s[i] {
		case '<':
			depth++
		case '>':
			depth--
		case sep:
			if depth == 0 {
				parts = append(parts, s[start:i])
				start = i + 1
			}
		}
	}
	parts = append(parts, s[start:])
	return parts
}

// EmitPlan holds the topological order and cycle information for Zod emission.
type EmitPlan struct {
	Order  []string                   // type names in dependency order (leaves first)
	Cycles map[string]map[string]bool // parentType → set of field type names needing getter syntax
}

// transitiveReachable finds all types reachable from the given root set.
func transitiveReachable(roots map[string]bool, defs map[string]typemap.TypeDef) map[string]bool {
	reachable := make(map[string]bool)
	var visit func(name string)
	visit = func(name string) {
		if reachable[name] {
			return
		}
		reachable[name] = true
		def, ok := defs[name]
		if !ok {
			return
		}
		if def.Kind == typemap.TypeDefInterface {
			for _, f := range def.Fields {
				// Extract referenced type names from the TS type string.
				for _, ref := range extractTypeRefs(f.Type) {
					visit(ref)
				}
			}
			// Follow extends relationships — base types are dependencies.
			for _, ext := range def.Extends {
				for _, ref := range extractTypeRefs(ext) {
					visit(ref)
				}
			}
		}
	}
	for name := range roots {
		visit(name)
	}
	return reachable
}

// topologicalSort produces a dependency-ordered list of types to emit.
// Returns cycle info for types that need getter syntax.
func topologicalSort(reachable map[string]bool, defs map[string]typemap.TypeDef) EmitPlan {
	// Build adjacency: type → types it depends on.
	// Self-references are tracked separately since they aren't graph edges
	// but still require z.lazy() wrapping.
	deps := make(map[string][]string)
	selfRefs := make(map[string]bool)
	for name := range reachable {
		def, ok := defs[name]
		if !ok {
			continue
		}
		if def.Kind == typemap.TypeDefInterface {
			for _, f := range def.Fields {
				for _, ref := range extractTypeRefs(f.Type) {
					if !reachable[ref] {
						continue
					}
					if ref == name {
						selfRefs[name] = true
					} else {
						deps[name] = append(deps[name], ref)
					}
				}
			}
			// Extends are also dependencies — base schemas must emit first.
			for _, ext := range def.Extends {
				for _, ref := range extractTypeRefs(ext) {
					if !reachable[ref] {
						continue
					}
					if ref != name {
						deps[name] = append(deps[name], ref)
					}
				}
			}
		}
	}

	// Detect cycles using DFS coloring.
	type color int
	const (
		white color = iota
		gray
		black
	)
	colors := make(map[string]color)
	cycles := make(map[string]map[string]bool)
	var order []string

	var dfs func(name string)
	dfs = func(name string) {
		if colors[name] == black {
			return
		}
		if colors[name] == gray {
			// Cycle detected — marked by caller.
			return
		}
		colors[name] = gray
		for _, dep := range deps[name] {
			if colors[dep] == gray {
				// Back-edge: name depends on dep which is still being processed → cycle.
				if cycles[name] == nil {
					cycles[name] = make(map[string]bool)
				}
				cycles[name][dep] = true
			} else {
				dfs(dep)
			}
		}
		colors[name] = black
		order = append(order, name)
	}

	// Sort for deterministic output.
	names := make([]string, 0, len(reachable))
	for name := range reachable {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		dfs(name)
	}

	// Merge self-references into cycles map.
	for name := range selfRefs {
		if cycles[name] == nil {
			cycles[name] = make(map[string]bool)
		}
		cycles[name][name] = true
	}

	return EmitPlan{Order: order, Cycles: cycles}
}

// extractTypeRefs pulls named type references from a TS type string.
// "Foo[]" → ["Foo"], "Record<string, Bar>" → ["Bar"], "Foo" → ["Foo"]
func extractTypeRefs(tsType string) []string {
	// Skip primitive types.
	switch tsType {
	case "string", "number", "boolean", "unknown", "void", "null", "undefined", "never":
		return nil
	}

	// Array: "Foo[]" → Foo
	if before, ok := strings.CutSuffix(tsType, "[]"); ok {
		elem := before
		elem = strings.TrimPrefix(elem, "(")
		elem = strings.TrimSuffix(elem, ")")
		return extractTypeRefs(elem)
	}

	// Record: "Record<K, V>"
	if strings.HasPrefix(tsType, "Record<") {
		inner := tsType[len("Record<") : len(tsType)-1]
		parts := splitTopLevel(inner, ',')
		var refs []string
		for _, p := range parts {
			refs = append(refs, extractTypeRefs(strings.TrimSpace(p))...)
		}
		return refs
	}

	// Generic instantiation: "Foo<Bar, Baz>"
	if idx := strings.IndexByte(tsType, '<'); idx >= 0 {
		name := tsType[:idx]
		inner := tsType[idx+1 : len(tsType)-1]
		refs := []string{name}
		for _, p := range splitTopLevel(inner, ',') {
			refs = append(refs, extractTypeRefs(strings.TrimSpace(p))...)
		}
		return refs
	}

	// Inline object types: "{ foo: string; bar: number }"
	if strings.HasPrefix(tsType, "{") {
		return nil
	}

	// Union types: "A | B"
	if strings.Contains(tsType, " | ") {
		parts := strings.Split(tsType, " | ")
		var refs []string
		for _, p := range parts {
			refs = append(refs, extractTypeRefs(strings.TrimSpace(p))...)
		}
		return refs
	}

	// Named type.
	return []string{tsType}
}
